spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-214-125-106.eu-west-1.compute.amazonaws.com:5432/darj3s6rhgak0
    username: kfoxoogtvalmvf
    password: 772d8c99d1ca51684de1a2cf69c5343d3e1cf1533a5bcec591e3f3d76c6a2fd9
  #    url: jdbc:postgresql://localhost:5432/course
  #    username: user1
  #    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        search:
          default:
            derictory_provider: filesystem
            indexBase: indexpath

        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 126142912527-bbc4ul3lieu0vubskar8db93p84qopug.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

          facebook:
            clientId: 1166073094208212
            clientSecret: b5853c0acc30ec31eb4a9b06f6169af7
            scope:
              - email
              - public_profile
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

